version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--api=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.rabbitmqentry.address=:15672"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.udb.address=:5401"
      - "--certificatesresolvers.le.acme.email=lstuempeley@fh-bielefeld.de"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
    environment:
      - "NAMECOM_USERNAME=leonstue"
      - "NAMECOM_API_TOKEN=144a4a06be34f25e28d8c1786440e9e6fe2f6743"
      - "NAMECOM_SERVER=api.name.com"
    ports:
      - "8080:8080"
      - "80:80"
      - "15672:15672"
      - "443:443"
      - "5401:5401"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "~/cert/acme.json:/acme.json"

  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.whoami.rule=Host(`whoami.cyber-city.systems`) && PathPrefix(`/api`)
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.tls.certresolver=le

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`cyber-city.systems`)"
      - "traefik.http.routers.rabbitmq.entrypoints=rabbitmqentry"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.routers.rabbitmq.service=rabbitmq"
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ~/rabbitmq/log/:/var/log/rabbitmq/
      - ~/rabbitmqsetup/rabbitmq.json:/etc/rabbitmq/definitions.json
      - ~/rabbitmqsetup/rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  authentifizierung:
    image: "registry.digitalocean.com/cybercityregistry/authentifizierung:latest"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.authentifizierung.rule=Host(`auth.cyber-city.systems`)"
    - "traefik.http.routers.authentifizierung.entrypoints=https"
    - "traefik.http.routers.authentifizierung.tls.certresolver=le"
    volumes:
      - ~/authkeys/id_rsa.pem:/Authentification/id_rsa.pem
      - ~/authkeys/id_rsa_pub.pem:/Authentification/id_rsa_pub.pem
    restart: on-failure

  authdb:
    image: mariadb
    restart: on-failure
    volumes:
        - ~/authdbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ~/authdb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: authdbpw1234
      MARIADB_PASSWORD: authdbpw1234
      MARIADB_USER: auth
      MARIADB_DATABASE: auth

  gesundheitswesen_fr:
    image: "registry.digitalocean.com/cybercityregistry/gesundheitswesen_fr:latest"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.gesundheitswesen_fr.rule=Host(`gesundheitswesen.cyber-city.systems`)"
    - "traefik.http.routers.gesundheitswesen_fr.entrypoints=https"
    - "traefik.http.routers.gesundheitswesen_fr.tls.certresolver=le"
    restart: on-failure

  gesundheitswesen_ba:
    image: "registry.digitalocean.com/cybercityregistry/gesundheitswesen_ba:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gesundheitswesen_ba.rule=Host(`gesundheitswesen.cyber-city.systems`) && PathPrefix(`/api`)"
      - "traefik.http.routers.gesundheitswesen_ba.entrypoints=https"
      - "traefik.http.routers.gesundheitswesen_ba.tls.certresolver=le"
    restart: on-failure

  umwelt_fr:
    image: "registry.digitalocean.com/cybercityregistry/umwelt_fr:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umwelt_fr.rule=Host(`umwelt.cyber-city.systems`)"
      - "traefik.http.routers.umwelt_fr.entrypoints=https"
      - "traefik.http.routers.umwelt_fr.tls.certresolver=le"
    restart: on-failure

  umwelt_ba:
    image: "registry.digitalocean.com/cybercityregistry/umwelt_ba:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umwelt_ba.rule=Host(`umwelt.cyber-city.systems`)  && PathPrefix(`/api`)"
      - "traefik.http.routers.umwelt_ba.entrypoints=https"
      - "traefik.http.services.umwelt_ba.loadbalancer.server.port=8080"
      - "traefik.http.routers.umwelt_ba.tls.certresolver=le"
    restart: on-failure

  verkehrdb:
    image: mariadb
    restart: on-failure
    volumes:
        - ~/verkehr/init/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ~/verkehr:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: verkehrpw12345
      MARIADB_PASSWORD: verkehrpw12345
      MARIADB_USER: verkehr
      MARIADB_DATABASE: verkehr
    
  verkehr:
    restart: on-failure
    depends_on: 
      - verkehrdb
    image: "registry.digitalocean.com/cybercityregistry/verkehr:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verkehr.rule=Host(`verkehr.cyber-city.systems`)"
      - "traefik.http.routers.verkehr.entrypoints=https"
      - "traefik.http.routers.verkehr.tls.certresolver=le"
  

  rabbitmqsetup:
    image: "registry.digitalocean.com/cybercityregistry/rabbitmq-setup:latest"
    depends_on:
      - rabbitmq
    restart: on-failure

  unternehmendb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: cc_cj#&#2022
      POSTGRES_USER: cjadmin
    volumes:
      - ~/unternehmendbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/unternehmendb:/var/lib/postgresql/data
    command: -p 5401
    labels:
    - "traefik.enable=true"
    - "traefik.tcp.services.unternehmendb.loadbalancer.server.port=5401"
    - "traefik.tcp.routers.unternehmendb.rule=HostSNI(`*`)"
    - "traefik.tcp.routers.unternehmendb.entrypoints=udb"
    restart: on-failure

  landingpage_fr:
    image: "registry.digitalocean.com/cybercityregistry/landingpage_fr:latest"
    depends_on: 
      - landingpage_ba
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.landingpage_fr.rule=Host(`cyber-city.systems`)"
     - "traefik.http.routers.landingpage_fr.entrypoints=https"
     - "traefik.http.routers.landingpage_fr.tls.certresolver=le"
    restart: on-failure

  landingpage_ba:
    image: "registry.digitalocean.com/cybercityregistry/landingpage_ba:latest"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.landingpage_ba.rule=Host(`cyber-city.systems`) && PathPrefix(`/api`)"
     - "traefik.http.routers.landingpage_ba.entrypoints=https"
     - "traefik.http.routers.landingpage_ba.tls.certresolver=le"
    restart: on-failure

  kultur_fr:
    restart: on-failure
    image: "registry.digitalocean.com/cybercityregistry/kultur_fr:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kultur_fr.rule=Host(`kultur.cyber-city.systems`)"
      - "traefik.http.routers.kultur_fr.entrypoints=https"
      - "traefik.http.routers.kultur_fr.tls.certresolver=le"

  kultur_ba:
    restart: on-failure
    image: "registry.digitalocean.com/cybercityregistry/kultur_ba:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kultur_ba.rule=Host(`kultur.cyber-city.systems`) && PathPrefix(`/api`)"
      - "traefik.http.routers.kultur_ba.entrypoints=https"
      - "traefik.http.routers.kultur_ba.tls.certresolver=le"
  
  kulturdb:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: kulturdbpw12345
      POSTGRES_USER: kulturdbuser
    volumes:
      - ~/kulturdbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/kulturdb:/var/lib/postgresql/data

  gesunddb:
    image: mongo
    restart: on-failure
    command: mongod --port 7777
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  unternehmensregister_fr:
    image: "registry.digitalocean.com/cybercityregistry/unternehmensregister_fr:latest"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unternehmensregister_fr.rule=Host(`unternehmensregister.cyber-city.systems`)"
      - "traefik.http.routers.unternehmensregister_fr.entrypoints=https"
      - "traefik.http.routers.unternehmensregister_fr.tls.certresolver=le"

  unternehmensregister_ba:
    image: "registry.digitalocean.com/cybercityregistry/unternehmensregister_ba:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unternehmensregister_ba.rule=Host(`unternehmensregister.cyber-city.systems`) && PathPrefix(`/api`)"
      - "traefik.http.routers.unternehmensregister_ba.entrypoints=https"
      - "traefik.http.routers.unternehmensregister_ba.tls.certresolver=le"
    environment:
      HOST: unternehmendb
      PORT: 5401
      DB: cjadmin
      USER: cjadmin
      PW: 'cc_cj#&#2022'
    restart: on-failure