version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.rabbitmqentry.address=:15672"
    ports:
      - "80:80"
      - "8080:8080"
      - "15672:15672"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rabbitmq:
      image: "rabbitmq:3-management"
      container_name: "rabbitmq"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbitmq.rule=Host(`cyber-city.systems`)"
        - "traefik.http.routers.rabbitmq.entrypoints=rabbitmqentry"
        - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
        - "traefik.http.routers.rabbitmq.service=rabbitmq"
        - "traefik.docker.network=traefik_default"
      volumes:
        - ~/rabbitmq/data/:/var/lib/rabbitmq/mnesia
        - ~/rabbitmq/log/:/var/log/rabbitmq/
        - ~/rabbitmqsetup/rabbitmq.json:/etc/rabbitmq/definitions.json
        - ~/rabbitmqsetup/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  
  authentifikation:
    image: "registry.digitalocean.com/cybercityregistry/authentifizierung:latest"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.authentifikation.rule=Host(`auth.cyber-city.systems`)"
    - "traefik.http.routers.authentifikation.entrypoints=web"

  authdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: authdbpw1234
      POSTGRES_USER: auth

  gesundheitswesen_fr:
    image: "registry.digitalocean.com/cybercityregistry/gesundheitswesen_frontend:latest"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.gesundheitswesen.rule=Host(`gesundheitswesen.cyber-city.systems`)"
    - "traefik.http.routers.gesundheitswesen.entrypoints=web"

  gesundheitswesen_ba:
    image: "registry.digitalocean.com/cybercityregistry/gesundheitswesen_backend:latest"
    labels:
    - "traefik.enable=false"

  umwelt:
    image: "registry.digitalocean.com/cybercityregistry/umwelt:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umwelt.rule=Host(`umwelt.cyber-city.systems`)"
      - "traefik.http.routers.umwelt.entrypoints=web"

  verkehrdb:
    image: mariadb
    restart: always
    volumes:
        - ~/verkehr/init/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ~/verkehr:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: verkehrpw12345
      MARIADB_PASSWORD: verkehrpw12345
      MARIADB_USER: verkehr
      MARIADB_DATABASE: verkehr
    
  verkehr:
    depends_on: 
      - verkehrdb
    image: "registry.digitalocean.com/cybercityregistry/verkehr:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verkehr.rule=Host(`verkehr.cyber-city.systems`)"
      - "traefik.http.routers.verkehr.entrypoints=web"
  

  rabbitmqsetup:
    image: "registry.digitalocean.com/cybercityregistry/rabbitmq-setup:latest"
    depends_on:
      - rabbitmq

  # kultur:
  #   image: "cybercity-kultur:latest"

  #   container_name: "cybercity-kultur"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.kultur.rule=Host(`kultur.cyber-city.systems`)"
  #     - "traefik.http.routers.kultur.entrypoints=web"

  # landingpage:
  #   image: "cybercity-landingpage:latest"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.landingpage.rule=Host(`cyber-city.systems`)"
  #     - "traefik.http.routers.landingpage.entrypoints=web"



  # unternehmensregister:
  #   image: "cybercity-unternehmensregister:latest"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.unternehmensregister.rule=Host(`unternehmensregister.cyber-city.systems`)"
  #     - "traefik.http.routers.unternehmensregister.entrypoints=web"

  