name: dc-config

on:
  #run on push
  push:
    branches: [main]

  #run manually
  workflow_dispatch:

env:
  REGISTRY: "registry.digitalocean.com/cybercityregistry"

jobs:
  deploy_and_run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Stop docker-compose
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            cd ~/docker
            docker-compose stop
      - name: Deploy script
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -azvr --delete
          path: src/
          remote_path: ~/docker
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY}}
          remote_key_pass: ${{ secrets.SSH_PASSPHRASE }}

      - name: Start Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY}}
          script: |
            cd ~/docker
            docker-compose pull
            docker-compose up -d --force-recreate --remove-orphans
